extends: static.yaml
checkpoint:
  output_dir: output/crystallization-187800/static
inputs:
  data_config: configs/data/loaders/static_al_crystallization_step187800.yaml
real_md:
  time_series:
    paper_enabled: true
