learning_rate: 0.01
batch_size: 8192
epochs: 100
decay_rate: 0.0002
gpu: True
log_every_n_steps: 5
num_workers: 4
scheduler_gamma: 0.5
scheduler_name: onecycle

feature_transform_loss_scale: 0.001
reconstruction_loss_scale: 0.005