defaults:
  - training: autoencoder_train
  - data: autoencoder_Al_basic 
  - model: autoencoder_basic
project_name: pointnet
experiment_name: PnAE_Folding_64_SWA_centered_latent_size_256
wandb_mode: online
experiment_tags:
  - autoencoder
  - RDF
  - SWA
  - Transformer
  - Folding