defaults:
  - training: autoencoder_train
  - data: autoencoder_Al_basic 
  - model: autoencoder_basic
project_name: pointnet
experiment_name: PointNetAE_RDF_wasserstein_32_points
# wandb_mode: online
wandb_mode: offline
