defaults:
  - data: data_ae_Al_16
project_name: pointnet
experiment_name: PnAE_Folding2Step_CD_Repulsion_RotCon_16_l8_no_edges
wandb_mode: online
experiment_tags:
  - SWA
  - Folding
  - centered
  - RotationConsistency
  - no_edges

latent_size: 16
type:  PointNetAE_Folding                   # PointNetAE_MLP
loss: chamfer_regularized_encoder_loss_repulsion
kl_beta_start: 0.0
kl_beta: 1.0
kl_beta_warmup: 10_000
kl_beta_schedule: linear
torch_compile: True

learning_rate: 0.003
batch_size: 4096

enable_swa: False 
swa_epoch_start: 1000 
epochs: 1000

decay_rate: 0.003
gpu: True
devices: 0
log_every_n_steps: 5
num_workers: 6
scheduler_gamma: 0.5
scheduler_name: OneCycle

feature_transform_loss_scale: 0.001
rotation_loss_scale: 0.1
reconstruction_loss_scale: 0.5
l1_latent_loss_scale: 0.01
dropout_rate: 0.5