defaults:
  - data: data_ae_Al_80
project_name: pointnet
experiment_name: PnAE_Folding2Step_CD_Repulsion_RotCon_80_l16_no_edges
wandb_mode: online
experiment_tags:
  - SWA
  - Folding
  - centered
  - RotationConsistency
  - no_edges

latent_size: 6
type:  PointNetAE_Folding_Sphere  
loss: chamfer_regularized_encoder_loss_repulsion
torch_compile: True

learning_rate: 0.004
batch_size: 6096

enable_swa: False
swa_epoch_start: 1000 
epochs: 100

decay_rate: 0.003
gpu: True
devices: 0
log_every_n_steps: 5
num_workers: 4
scheduler_gamma: 0.5
scheduler_name: Cosine

feature_transform_loss_scale: 0.001
rotation_loss_scale: 0.05
reconstruction_loss_scale: 0.5
l1_latent_loss_scale: 0.01
dropout_rate: 0.3
