defaults:
  - data: autoencoder_Al_basic 
project_name: pointnet
experiment_name: PnAE_Trans_Folding_KL_RDF_64_l256
wandb_mode: offline
experiment_tags:
  - autoencoder
  - RDF
  - SWA
  - Transformer
  - Folding
  - centered
  - SWA

latent_size: 8
type: PointNetAE_Transformer_Folding
loss: chamfer_kl_divergence
torch_compile: True

learning_rate: 0.0004
batch_size: 2048
epochs: 4000
decay_rate: 0.004
gpu: True
log_every_n_steps: 5
num_workers: 6
scheduler_gamma: 0.5
scheduler_name: chained

feature_transform_loss_scale: 0.001
reconstruction_loss_scale: 0.5

