defaults:
  - data: autoencoder_Al_basic 
project_name: pointnet
experiment_name: PnAE_MLP_KLRDF_long_64_l8
wandb_mode: online
experiment_tags:
  - autoencoder
  - RDF
  - SWA
  - Transformer
  - Folding
  - centered
  - SWA

latent_size: 8
type:  PointNetAE_MLP              
loss: chamfer_kl_divergence    #  chamfer_regularized_encoder
torch_compile: True

learning_rate: 0.0002
batch_size: 16384
epochs: 4000
decay_rate: 0.004
gpu: True
devices: auto
log_every_n_steps: 5
num_workers: 6
scheduler_gamma: 0.5
scheduler_name: chained

feature_transform_loss_scale: 0.001
reconstruction_loss_scale: 0.5

