defaults:
  - data: autoencoder_Al
project_name: pointnet
experiment_name: PnAE_Folding2Step_CD_Repulsion_RotCon_64_l16_no_edges
wandb_mode: online
experiment_tags:
  - SWA
  - Folding
  - centered
  - RotationConsistency
  - no_edges

latent_size: 16
type:  PointNetAE_Folding                   # PointNetAE_MLP
loss: chamfer_regularized_encoder_loss_repulsion
kl_beta_start: 0.0
kl_beta: 1.0
kl_beta_warmup: 10_000
kl_beta_schedule: linear
torch_compile: True

learning_rate: 0.005
batch_size: 8192

enable_swa: True
swa_epoch_start: 1000 
epochs: 1500

decay_rate: 0.01
gpu: True
devices: 0
log_every_n_steps: 5
num_workers: 8
scheduler_gamma: 0.5
scheduler_name: Cosine

feature_transform_loss_scale: 0.001
rotation_loss_scale: 0.03
reconstruction_loss_scale: 0.5

