defaults:
  - training: autoencoder_s2s_train
  - data: autoencoder_Al_basic 
  - model: autoencoder_s2s
project_name: pointnet
experiment_name: s2s_ResNet_KLRDF_64_latent_256
wandb_mode: offline
experiment_tags:
  - autoencoder
  - S2S
  - ResNet
  - SWA
  - centered