defaults:
  - data: data_ae_Al_80_small.yaml
project_name: pointnet
experiment_name: SPD_${decoder.name}_l${latent_size}_P${data.num_points}_${loss}_${batch_size}
wandb_mode: offline

model_type: spd
latent_size: 36
encoder: 
  name: PnE_VN
  kwargs:
    latent_size: ${latent_size}
    # hidden_dim1: 360
    # hidden_dim2: 720
    
decoder: 
  name: FoldingSphereAttn
  kwargs: 
    latent_size: ${latent_size}
    num_points: ${data.num_points}
    dropout_rate: 0.1
    n_shells: 2
    R1: 0.5
    R2: 1.0
    hidden_dim: 512
    R_att: 0.5
    learnable_template: False

rot_net:
  name: Rot6DHead
  kwargs:
    hidden: 256
    use_attention: True

rotation_mode: sixd_head

loss: Sinkhorn
sinkhorn_blur_schedule:
  enable: true
  start: 0.1
  end: 0.01
  start_epoch: 0
  duration_epochs: ${epochs}
max_samples: 0  # no limit
torch_compile: True

learning_rate: 0.004
batch_size: 2048  

enable_swa: False
swa_epoch_start: 1000 
epochs: 24

gpu: True
devices: 0
log_every_n_steps: 5
num_workers: 4
scheduler_gamma: 0.5
scheduler_name: Cosine

decay_rate: 0.0004
kl_latent_loss_scale: 0.02
pdist_loss_scale: 0.00
kabsch_rotation_loss_scale: 0.000
