defaults:
  - data: data_ae_Al_80
project_name: pointnet
experiment_name: SPD_${decoder.name}_l${latent_size}_P${data.num_points}_${loss}_${batch_size}
wandb_mode: online
experiment_tags:
  - SWA
  - Folding
  - centered
  - RotationConsistency
  - no_edges
model_type: spd
latent_size: 72
encoder: 
  name: PnE_VN
  kwargs:
    latent_size: ${latent_size}
    hidden_dim1: 384
    hidden_dim2: 1024
decoder: 
  name: FoldingSphereAttn
  kwargs: 
    latent_size: ${latent_size}
    num_points: ${data.num_points}
    dropout_rate: 0.1
    n_shells: 2
    R1: 0.5
    R2: 1.0
    hidden_dim: 384
    R_att: 0.40

loss: Sinkhorn
max_samples: 0  # no limit
torch_compile: True

learning_rate: 0.005
batch_size: 1024

enable_swa: False
swa_epoch_start: 1000 
epochs: 100

gpu: True
devices: 0
log_every_n_steps: 5
num_workers: 6
scheduler_gamma: 0.5
scheduler_name: OneCycle

decay_rate: 0.002
kl_latent_loss_scale: 0.03
