defaults:
  - data: data_synth_no_perturb
project_name: pointnet
experiment_name: synth_SPD_${decoder.name}_l${latent_size}_P${data.num_points}_${loss}_${batch_size}
wandb_mode: online

model_type: spd
latent_size: 240

# Optional: Load pretrained supervised encoder
load_supervised_checkpoint: False  # Set to True to load pretrained weights
supervised_checkpoint_path: output/supervised_encoder/2025-11-07/19-36-50/supervised_encoder_VN_DGCNN_l36_bs1024_lr0.0060_rotsixd_head_loss_epochloss_epoch=00.ckpt

encoder: 
  name: VN_DGCNN_Refined # PnE_VN
  kwargs:
    latent_size: ${latent_size}
    feature_dims: [128, 128, 256, 512, 1024]
    pooling: "max"
    

decoder: 
  name: VQMoEv2
  kwargs: 
    latent_size: ${latent_size}
    num_points: ${data.num_points}
    vq_size: 128
    use_vq: True
    router_hidden: 256
    transformer_hidden: 256
    transformer_layers: 3
    transformer_heads: 6
    lattice_hidden: 256
    amorphous_hidden: 256

rot_net:
  name: vn_rotation_head
  kwargs:
    hidden: 256
    use_attention: True

rotation_mode: vn_rotation_head

loss: sinkhorn+chamfer
sinkhorn_blur: 0.05
sinkhorn_blur_schedule:
  enable: true
  start: 0.05
  end: 0.01
  start_epoch: 0
  duration_epochs: ${epochs}
max_samples: 0  # no limit
torch_compile: True

learning_rate: 0.005
batch_size: 380

enable_swa: False
swa_epoch_start: 1000 
epochs: 900

gpu: True
devices: [0]
ddp_find_unused_parameters: True
log_every_n_steps: 5
num_workers: 6
scheduler_gamma: 0.5
scheduler_name: Cosine

decay_rate: 0.0004
kl_latent_loss_scale: 0.02
pdist_loss_scale: 0.00
ortho_scale: 0.01
kabsch_rotation_loss_scale: 0.000
