#!/usr/bin/env python3
"""Run one position-conditioned Zr trajectory from an archived thermal structure.

These are new fixed-cell Langevin-NVT trajectories.  The source files contain no
velocities or Nose-Hoover state, so this cannot be an exact continuation of the
original MD trajectory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = (
    REPOSITORY_ROOT
    / "output/synthetic_data/"
    "zr_initial_160ps_langevin_1150K_10ps_reconstructed_meam_zbl1_provisional_20260903"
)
SOURCE_ROOT = REPOSITORY_ROOT / "datasets/Zr/initial_configurations"
LIBRARY_POTENTIAL = REPOSITORY_ROOT / "datasets/potentials/Becker2020_Zr.library.meam"
PARAMETER_POTENTIAL = REPOSITORY_ROOT / "datasets/potentials/Becker2020_Zr.meam"

EXPECTED_ATOM_COUNT = 1_024_000
SOURCE_TIMESTEPS = {
    "160ps": 700_000,
}
RANDOM_SEEDS = {
    "160ps": (160_013, 160_019),
}

TEMPERATURE_K = 1150.0
TIMESTEP_FS = 2.0
DURATION_PS = 10.0
RUN_STEPS = 5_000
SAMPLE_INTERVAL_STEPS = 50
THERMOSTAT_TIME_FS = 200.0
MPI_RANKS = 32
EXPECTED_FRAME_COUNT = RUN_STEPS // SAMPLE_INTERVAL_STEPS + 1
SCHEMA_VERSION = 1
RUNNER_PATH = OUTPUT_ROOT / "runner.json"
RUNNER_LOG_PATH = OUTPUT_ROOT / "campaign_runner.log"
ANALYSIS_CONFIG_PATH = REPOSITORY_ROOT / "configs/analysis/temporal_Zr_initial160_Multi_GF.yaml"


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _write_json_atomic(path: Path, document: object) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(document, handle, indent=2)
        handle.write("\n")
    temporary.replace(path)


def _load_json(path: Path) -> dict[str, object]:
    with path.open("r", encoding="utf-8") as handle:
        document = json.load(handle)
    if not isinstance(document, dict):
        raise TypeError(f"Expected a JSON object in {path}, got {type(document).__name__}.")
    return document


def _read_source_header(path: Path, expected_timestep: int) -> list[list[float]]:
    with path.open("r", encoding="utf-8") as handle:
        header = [handle.readline().rstrip("\n") for _ in range(9)]
    if header[0] != "ITEM: TIMESTEP" or int(header[1]) != expected_timestep:
        raise ValueError(
            f"Unexpected source timestep in {path}: expected={expected_timestep}, "
            f"header={header[:2]!r}."
        )
    if header[2] != "ITEM: NUMBER OF ATOMS" or int(header[3]) != EXPECTED_ATOM_COUNT:
        raise ValueError(
            f"Unexpected atom count in {path}: expected={EXPECTED_ATOM_COUNT}, "
            f"header={header[2:4]!r}."
        )
    if header[4] != "ITEM: BOX BOUNDS pp pp pp":
        raise ValueError(f"Expected a fully periodic orthorhombic box in {path}, got {header[4]!r}.")
    bounds = [[float(value) for value in line.split()] for line in header[5:8]]
    if any(len(axis) != 2 or axis[1] <= axis[0] for axis in bounds):
        raise ValueError(f"Invalid box bounds in {path}: {bounds!r}.")
    if header[8].split() != ["ITEM:", "ATOMS", "id", "type", "x", "y", "z"]:
        raise ValueError(
            f"Expected source atom columns 'id type x y z' in {path}, got {header[8]!r}."
        )
    return bounds


def _render_lammps_input(
    *, source: Path, source_timestep: int, velocity_seed: int, thermostat_seed: int
) -> str:
    return f"""# Position-conditioned Zr dynamics generated by PointCloudMaterials.
# This is a new fixed-cell Langevin-NVT path, not an exact NPT restart.
log lammps.log
units metal
dimension 3
boundary p p p
atom_style atomic

region placeholder block 0 1 0 1 0 1 units box
create_box 1 placeholder
read_dump {source} {source_timestep} x y z box yes add yes replace no trim no scaled no wrapped yes
reset_timestep 0

mass 1 91.224
pair_style meam/c
pair_coeff * * ../../potential/Becker2020_Zr.library.meam Zr ../../potential/Becker2020_Zr.meam Zr
neighbor 2.0 bin
neigh_modify delay 0 every 1 check yes

timestep {TIMESTEP_FS / 1000.0:.12g}
velocity all create {TEMPERATURE_K:.12g} {velocity_seed} mom yes rot no dist gaussian loop all
fix remove_drift all momentum 100 linear 1 1 1
fix integrate all nve
fix thermostat all langevin {TEMPERATURE_K:.12g} {TEMPERATURE_K:.12g} {THERMOSTAT_TIME_FS / 1000.0:.12g} {thermostat_seed} zero yes

thermo {SAMPLE_INTERVAL_STEPS}
thermo_style custom step time temp press vol pe ke etotal
thermo_modify format float %.16g flush yes
dump trajectory all custom {SAMPLE_INTERVAL_STEPS} trajectory.lammpstrj id type x y z
dump_modify trajectory sort id format line "%d %d %.9g %.9g %.9g"

print "ZR_DYNAMICS_BEGIN"
run {RUN_STEPS}
write_restart final.restart.bin
print "ZR_DYNAMICS_COMPLETE"
"""


def _environment() -> dict[str, str]:
    environment = os.environ.copy()
    environment.update(
        {
            "OMP_NUM_THREADS": "1",
            "OMP_DYNAMIC": "FALSE",
            "MPIR_CVAR_CH4_NETMOD": "ofi",
            "FI_PROVIDER": "tcp",
        }
    )
    environment["LD_LIBRARY_PATH"] = str(Path(sys.prefix) / "lib") + (
        f":{environment['LD_LIBRARY_PATH']}" if environment.get("LD_LIBRARY_PATH") else ""
    )
    return environment


def _executables() -> tuple[Path, Path]:
    lammps = Path(sys.prefix) / "bin/lmp"
    mpiexec = Path(sys.prefix) / "bin/mpiexec"
    missing = [str(path) for path in (lammps, mpiexec) if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            "The local Zr campaign requires the LAMMPS and MPICH executables installed in "
            f"the active Python environment. Missing: {missing}. Run this script with "
            f"{REPOSITORY_ROOT / '.venv/bin/python'}."
        )
    return lammps, mpiexec


def prepare() -> dict[str, object]:
    if OUTPUT_ROOT.exists():
        raise FileExistsError(
            f"Campaign root already exists and will not be overwritten: {OUTPUT_ROOT}."
        )
    _executables()
    for potential in (LIBRARY_POTENTIAL, PARAMETER_POTENTIAL):
        if not potential.is_file():
            raise FileNotFoundError(f"Required reconstructed Zr potential file is missing: {potential}.")

    potential_dir = OUTPUT_ROOT / "potential"
    branch_root = OUTPUT_ROOT / "branches"
    potential_dir.mkdir(parents=True)
    branch_root.mkdir()
    shutil.copy2(LIBRARY_POTENTIAL, potential_dir / LIBRARY_POTENTIAL.name)
    shutil.copy2(PARAMETER_POTENTIAL, potential_dir / PARAMETER_POTENTIAL.name)

    branches: list[dict[str, object]] = []
    for index, (label, source_timestep) in enumerate(SOURCE_TIMESTEPS.items()):
        source = SOURCE_ROOT / f"{label}.pos"
        if not source.is_file():
            raise FileNotFoundError(f"Required Zr inherent configuration is missing: {source}.")
        bounds = _read_source_header(source, source_timestep)
        velocity_seed, thermostat_seed = RANDOM_SEEDS[label]
        branch_dir = branch_root / label
        branch_dir.mkdir()
        input_path = branch_dir / "in.lammps"
        input_path.write_text(
            _render_lammps_input(
                source=source.resolve(),
                source_timestep=source_timestep,
                velocity_seed=velocity_seed,
                thermostat_seed=thermostat_seed,
            ),
            encoding="utf-8",
        )
        metadata: dict[str, object] = {
            "schema_version": SCHEMA_VERSION,
            "state": "prepared",
            "prepared_at_utc": _utc_now(),
            "index": index,
            "label": label,
            "source": str(source.resolve()),
            "source_timestep": source_timestep,
            "source_sha256": _sha256(source),
            "source_box_bounds_A": bounds,
            "atom_count": EXPECTED_ATOM_COUNT,
            "velocity_seed": velocity_seed,
            "thermostat_seed": thermostat_seed,
        }
        _write_json_atomic(branch_dir / "metadata.json", metadata)
        branches.append(metadata)

    manifest: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "state": "prepared",
        "prepared_at_utc": _utc_now(),
        "output_root": str(OUTPUT_ROOT),
        "scientific_scope": (
            "Position-conditioned fixed-cell Langevin-NVT trajectory initialized from an "
            "archived finite-temperature coordinate snapshot; not an exact restart of the "
            "source NPT simulation."
        ),
        "temperature_provenance": (
            "1150 K is inferred from the Zr nucleation snapshot reported in Fig. 7 of "
            "Becker et al., Phys. Rev. B 102, 104205 (2020); the .pos files do not store "
            "temperature, velocities, or thermostat/barostat state."
        ),
        "potential_provenance": (
            "2NN-MEAM files reconstructed from Table I and Sec. II.A of Becker et al.; "
            "the authors' original potential files were not published with the dataset. "
            "LAMMPS' default ZBL short-range repulsion is retained because disabling it "
            "causes the negative-d Rose form to collapse."
        ),
        "known_compatibility_limit": (
            "The reconstructed potential reproduces the bcc reference cohesive energy, but "
            "the authors' exact potential file and the source velocities are unavailable. "
            "Treat this campaign as provisional dynamics augmentation."
        ),
        "protocol": {
            "ensemble": "fixed-cell Langevin NVT",
            "temperature_K": TEMPERATURE_K,
            "timestep_fs": TIMESTEP_FS,
            "duration_ps": DURATION_PS,
            "run_steps": RUN_STEPS,
            "sample_interval_steps": SAMPLE_INTERVAL_STEPS,
            "sample_interval_ps": SAMPLE_INTERVAL_STEPS * TIMESTEP_FS / 1000.0,
            "expected_frame_count": EXPECTED_FRAME_COUNT,
            "thermostat_time_fs": THERMOSTAT_TIME_FS,
            "mpi_ranks": MPI_RANKS,
            "lammps_pair_style": "meam/c",
        },
        "potential": {
            "library_file": "potential/Becker2020_Zr.library.meam",
            "library_sha256": _sha256(potential_dir / LIBRARY_POTENTIAL.name),
            "parameter_file": "potential/Becker2020_Zr.meam",
            "parameter_sha256": _sha256(potential_dir / PARAMETER_POTENTIAL.name),
        },
        "branches": branches,
    }
    _write_json_atomic(OUTPUT_ROOT / "manifest.json", manifest)
    return manifest


def _scan_trajectory(path: Path) -> dict[str, object]:
    if str(REPOSITORY_ROOT) not in sys.path:
        sys.path.insert(0, str(REPOSITORY_ROOT))
    from src.data_utils.temporal_lammps_dataset import TemporalLAMMPSDumpDataset

    scan = TemporalLAMMPSDumpDataset.scan_dump_file(path)
    expected_timesteps = list(range(0, RUN_STEPS + 1, SAMPLE_INTERVAL_STEPS))
    observed_timesteps = scan.timesteps.tolist()
    if scan.frame_count != EXPECTED_FRAME_COUNT or observed_timesteps != expected_timesteps:
        raise RuntimeError(
            f"Trajectory frame contract failed for {path}: expected_count={EXPECTED_FRAME_COUNT}, "
            f"observed_count={scan.frame_count}, expected_timesteps={expected_timesteps[:3]}..."
            f"{expected_timesteps[-3:]}, observed_timesteps={observed_timesteps[:3]}..."
            f"{observed_timesteps[-3:]}."
        )
    if scan.num_atoms != EXPECTED_ATOM_COUNT or scan.atom_columns != ("id", "type", "x", "y", "z"):
        raise RuntimeError(
            f"Trajectory atom contract failed for {path}: expected_atoms={EXPECTED_ATOM_COUNT}, "
            f"observed_atoms={scan.num_atoms}, columns={scan.atom_columns}."
        )
    return {
        "frame_count": scan.frame_count,
        "first_timestep": observed_timesteps[0],
        "last_timestep": observed_timesteps[-1],
        "atom_columns": list(scan.atom_columns),
    }


def run_branch(label: str) -> dict[str, object]:
    if label not in SOURCE_TIMESTEPS:
        raise KeyError(f"Unknown branch label {label!r}; expected one of {list(SOURCE_TIMESTEPS)}.")
    manifest_path = OUTPUT_ROOT / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"Prepared campaign manifest is missing: {manifest_path}.")
    branch_dir = OUTPUT_ROOT / "branches" / label
    metadata_path = branch_dir / "metadata.json"
    metadata = _load_json(metadata_path)
    if metadata.get("state") == "complete":
        print(f"{label}: already complete", flush=True)
        return metadata
    partial = [
        path.name
        for path in (
            branch_dir / "trajectory.lammpstrj",
            branch_dir / "final.restart.bin",
            branch_dir / "lammps.log",
        )
        if path.exists()
    ]
    if partial:
        raise RuntimeError(
            f"{label}: refusing to overwrite incomplete output files {partial} in {branch_dir}."
        )

    lammps, mpiexec = _executables()
    command = [str(mpiexec), "-n", str(MPI_RANKS), str(lammps), "-in", "in.lammps"]
    started = time.monotonic()
    print(f"{label}: starting {' '.join(command)}", flush=True)
    stdout_path = branch_dir / "stdout.log"
    with stdout_path.open("w", encoding="utf-8") as stdout:
        process = subprocess.Popen(
            command,
            cwd=branch_dir,
            env=_environment(),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        saw_lammps_error = False
        saw_completion_marker = False
        try:
            for line in process.stdout:
                stdout.write(line)
                stdout.flush()
                if line.startswith("ERROR:"):
                    saw_lammps_error = True
                if "ZR_DYNAMICS_COMPLETE" in line:
                    saw_completion_marker = True
                fields = line.split()
                if len(fields) == 8:
                    try:
                        step = int(fields[0])
                    except ValueError:
                        continue
                    if step % 500 == 0:
                        print(f"{label}: {line.strip()}", flush=True)
        except KeyboardInterrupt:
            process.terminate()
            process.wait()
            raise
        return_code = process.wait()
    if return_code != 0 or saw_lammps_error or not saw_completion_marker:
        raise RuntimeError(
            f"{label}: LAMMPS failed: return_code={return_code}, "
            f"saw_error={saw_lammps_error}, completion_marker={saw_completion_marker}. "
            f"Inspect {stdout_path} and {branch_dir / 'lammps.log'}."
        )

    trajectory = branch_dir / "trajectory.lammpstrj"
    restart = branch_dir / "final.restart.bin"
    missing = [str(path) for path in (trajectory, restart) if not path.is_file() or path.stat().st_size == 0]
    if missing:
        raise FileNotFoundError(f"{label}: LAMMPS completed without required artifacts: {missing}.")
    scan = _scan_trajectory(trajectory)
    elapsed_seconds = time.monotonic() - started
    metadata.update(
        {
            "state": "complete",
            "completed_at_utc": _utc_now(),
            "elapsed_seconds": elapsed_seconds,
            "trajectory": "trajectory.lammpstrj",
            "trajectory_size_bytes": trajectory.stat().st_size,
            "restart": "final.restart.bin",
            "restart_size_bytes": restart.stat().st_size,
            "scan": scan,
        }
    )
    _write_json_atomic(metadata_path, metadata)
    print(f"{label}: complete in {elapsed_seconds / 60.0:.1f} min", flush=True)
    return metadata


def run(labels: list[str]) -> None:
    selected = list(SOURCE_TIMESTEPS) if labels == ["all"] else labels
    if len(set(selected)) != len(selected):
        raise ValueError(f"Branch labels must be unique, got {selected}.")
    for label in selected:
        run_branch(label)


def summarize() -> dict[str, object]:
    rows = []
    for label in SOURCE_TIMESTEPS:
        metadata_path = OUTPUT_ROOT / "branches" / label / "metadata.json"
        if not metadata_path.is_file():
            raise FileNotFoundError(f"Missing branch metadata: {metadata_path}.")
        metadata = _load_json(metadata_path)
        if metadata.get("state") != "complete":
            raise RuntimeError(f"Cannot summarize incomplete branch {label}: state={metadata.get('state')!r}.")
        rows.append(
            {
                "label": label,
                "elapsed_seconds": metadata["elapsed_seconds"],
                "trajectory_size_bytes": metadata["trajectory_size_bytes"],
                "frame_count": metadata["scan"]["frame_count"],  # type: ignore[index]
            }
        )
    summary: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "state": "complete",
        "completed_at_utc": _utc_now(),
        "branch_count": len(rows),
        "total_elapsed_seconds": sum(float(row["elapsed_seconds"]) for row in rows),
        "total_trajectory_size_bytes": sum(int(row["trajectory_size_bytes"]) for row in rows),
        "branches": rows,
    }
    _write_json_atomic(OUTPUT_ROOT / "summary.json", summary)
    manifest = _load_json(OUTPUT_ROOT / "manifest.json")
    manifest["state"] = "complete"
    manifest["completed_at_utc"] = summary["completed_at_utc"]
    _write_json_atomic(OUTPUT_ROOT / "manifest.json", manifest)
    print(json.dumps(summary, indent=2), flush=True)
    return summary


def _pid_is_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def run_all_and_summarize() -> None:
    runner: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "state": "running",
        "pid": os.getpid(),
        "started_at_utc": _utc_now(),
        "log": str(RUNNER_LOG_PATH),
    }
    _write_json_atomic(RUNNER_PATH, runner)
    try:
        run(["all"])
        summary = summarize()
        runner["phase"] = "post_training_analysis"
        runner["simulation_completed_at_utc"] = _utc_now()
        _write_json_atomic(RUNNER_PATH, runner)
        if not ANALYSIS_CONFIG_PATH.is_file():
            raise FileNotFoundError(
                f"Post-training analysis config is missing: {ANALYSIS_CONFIG_PATH}."
            )
        from src.analysis.pipeline import run_post_training_analysis

        run_post_training_analysis(analysis_config_path=str(ANALYSIS_CONFIG_PATH))
    except BaseException as error:
        runner.update(
            {
                "state": "failed",
                "failed_at_utc": _utc_now(),
                "error_type": type(error).__name__,
                "error": str(error),
                "traceback": traceback.format_exc(),
            }
        )
        _write_json_atomic(RUNNER_PATH, runner)
        raise
    runner.update(
        {
            "state": "complete",
            "completed_at_utc": _utc_now(),
            "branch_count": summary["branch_count"],
            "total_elapsed_seconds": summary["total_elapsed_seconds"],
            "analysis_config": str(ANALYSIS_CONFIG_PATH),
        }
    )
    _write_json_atomic(RUNNER_PATH, runner)


def launch() -> dict[str, object]:
    if not (OUTPUT_ROOT / "manifest.json").is_file():
        raise FileNotFoundError(f"Prepared campaign manifest is missing: {OUTPUT_ROOT / 'manifest.json'}.")
    if RUNNER_PATH.exists():
        runner = _load_json(RUNNER_PATH)
        pid = int(runner.get("pid", -1))
        if runner.get("state") == "running" and _pid_is_alive(pid):
            raise RuntimeError(f"Campaign runner is already active with pid={pid}: {RUNNER_PATH}.")
        raise RuntimeError(
            f"Campaign runner metadata already exists and will not be overwritten: {RUNNER_PATH}."
        )
    with RUNNER_LOG_PATH.open("x", encoding="utf-8") as log_handle:
        process = subprocess.Popen(
            [sys.executable, str(Path(__file__).resolve()), "run-all"],
            cwd=REPOSITORY_ROOT,
            env=_environment(),
            stdin=subprocess.DEVNULL,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    runner = {
        "schema_version": SCHEMA_VERSION,
        "state": "running",
        "pid": process.pid,
        "launched_at_utc": _utc_now(),
        "log": str(RUNNER_LOG_PATH),
    }
    _write_json_atomic(RUNNER_PATH, runner)
    time.sleep(0.25)
    if process.poll() is not None:
        raise RuntimeError(
            f"Campaign runner exited immediately with return code {process.returncode}; "
            f"inspect {RUNNER_LOG_PATH}."
        )
    print(json.dumps(runner, indent=2), flush=True)
    return runner


def status() -> dict[str, object]:
    runner = _load_json(RUNNER_PATH) if RUNNER_PATH.is_file() else {"state": "not_launched"}
    pid = int(runner.get("pid", -1))
    branch_states = {}
    for label in SOURCE_TIMESTEPS:
        path = OUTPUT_ROOT / "branches" / label / "metadata.json"
        branch_states[label] = _load_json(path).get("state") if path.is_file() else "missing"
    document = {
        "runner": runner,
        "runner_process_alive": _pid_is_alive(pid) if pid > 0 else False,
        "branches": branch_states,
    }
    print(json.dumps(document, indent=2), flush=True)
    return document


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="action", required=True)
    subparsers.add_parser("prepare")
    run_parser = subparsers.add_parser("run")
    run_parser.add_argument(
        "labels",
        nargs="+",
        help="The label 160ps, or 'all'.",
    )
    subparsers.add_parser("summarize")
    subparsers.add_parser("launch")
    subparsers.add_parser("status")
    subparsers.add_parser("run-all", help=argparse.SUPPRESS)
    return parser.parse_args()


def main() -> None:
    args = _arguments()
    if args.action == "prepare":
        document = prepare()
        print(json.dumps({"output_root": document["output_root"], "branches": 1}, indent=2))
    elif args.action == "run":
        run(args.labels)
    elif args.action == "summarize":
        summarize()
    elif args.action == "launch":
        launch()
    elif args.action == "status":
        status()
    elif args.action == "run-all":
        run_all_and_summarize()
    else:
        raise AssertionError(f"Unhandled action {args.action!r}.")


if __name__ == "__main__":
    main()
