"""Lossless display packing of existing sample and embedding assets."""
import argparse
import base64
import json
from pathlib import Path
import numpy as np
from src.data.fixed_cohort.protocol import sha,write_json
from .dense_md import write_asset


def read_asset(path):return json.loads(path.read_text().split('=',2)[2].rstrip(';\n'))


def pack(publication):
    dest=Path(publication);records={}
    for kind in ('sample','travel'):
        original=dest/(kind+'-data')/'manifest.json'
        manifest=json.loads(original.read_text());folder=dest/(kind+'-compact');folder.mkdir(exist_ok=True)
        for frame,entry in manifest.items():
            entries=[e for group in entry.values() for e in group.values()] if kind=='sample' else list(entry['models'].values())
            for info in entries:
                source=dest/(kind+'-data')/Path(info['asset']).name
                data=read_asset(source);target=folder/source.name
                if kind=='sample':
                    # Uniform sample colors are generated by the viewer; retain
                    # all atom coordinates, geometric edges and cluster members.
                    reduced=dict(clusters=data['clusters'],patches={k:{f:p[f] for f in ('atom','xyz','edges')} for k,p in data['patches'].items()})
                    write_asset(target,info['key'],reduced,'CLUSTER_SAMPLES')
                else:
                    z=np.asarray(data.pop('z'),dtype=np.float64);packed=np.asarray(z,dtype='<f4')
                    if not np.array_equal(packed.astype(np.float64),z):raise ValueError(f'Non-float32 embedding values in {source}')
                    encoded=base64.b64encode(packed.tobytes()).decode('ascii');rows,width=packed.shape
                    # Restore ordinary JS number arrays, preserving the previous
                    # float64 arithmetic for differences, norms and graph weights.
                    script='window.TRAVEL_EMBEDDINGS=window.TRAVEL_EMBEDDINGS||{};(()=>{'
                    script+=f'const text=atob({json.dumps(encoded)}),bytes=Uint8Array.from(text,c=>c.charCodeAt(0)),view=new DataView(bytes.buffer);'
                    script+=f'const data={json.dumps(data,separators=(",",":"),allow_nan=False)};'
                    script+=f'data.z=Array.from({{length:{rows}}},(_,i)=>Array.from({{length:{width}}},(_,j)=>view.getFloat32(4*(i*{width}+j),true)));'
                    script+=f'window.TRAVEL_EMBEDDINGS[{json.dumps(info["key"])}]=data;}})();\n'
                    target.write_text(script)
                records[str(target.relative_to(dest))]=dict(source=str(source),source_sha256=sha(source),output_sha256=sha(target),before_bytes=source.stat().st_size,after_bytes=target.stat().st_size)
                info['asset']='../'+folder.name+'/'+target.name
        write_json(folder/'manifest.json',manifest)
    write_json(dest/'technical/rendering/compact-assets.json',dict(implementation_sha256=sha(__file__),lossless=True,original_assets_preserved=True,assets=records,
        before_bytes=sum(r['before_bytes'] for r in records.values()),after_bytes=sum(r['after_bytes'] for r in records.values())))
    print(dest, sum(r['before_bytes'] for r in records.values()),'->',sum(r['after_bytes'] for r in records.values()),flush=True)

if __name__=='__main__':
    p=argparse.ArgumentParser(__doc__);p.add_argument('--publication',required=True);a=p.parse_args();pack(a.publication)
